#!/bin/bash
#shellcheck disable=SC1091
# slug-files - Batch rename files to URL/filename-friendly slugs
set -euo pipefail
shopt -s inherit_errexit shift_verbose extglob nullglob

declare -r VERSION=1.0.0
#shellcheck disable=SC2155
declare -r SCRIPT_PATH=$(realpath -- "$0")
declare -r SCRIPT_DIR=${SCRIPT_PATH%/*} SCRIPT_NAME=${SCRIPT_PATH##*/}

declare -i VERBOSE=1

show_help() {
  cat <<HELP
Usage: $SCRIPT_NAME [-s|--sep_char CHAR] [-m|--max-len LEN] [-p|--preserve-case] [-n|--no-clobber] [-q|--quiet] file [file...]

Rename files to post-slug format

eg: $SCRIPT_NAME -pn /a/directory/*.txt
HELP
}

info() { >&2 echo "$SCRIPT_NAME:" "$1"; >&2 echo; }
die() { >&2 echo "$SCRIPT_NAME:" 'error:' "$2"; exit "$1"; }

declare -a Files=()
declare -- sep_char='-'
declare -i preserve_case=0 max_len=0 clobber=1
declare -- file dirname ext newfile

source post_slug.bash 2>/dev/null || {
  source "$SCRIPT_DIR"/post_slug.bash || die 1 "post_slug.bash not found in PATH or $SCRIPT_DIR"
}

while (($#)); do case $1 in
  -s|--sep_char)
      shift
      sep_char="${1:--}"
      sep_char="${sep_char:0:1}"
      ;;
  -m|--max-len)
      shift
      max_len=${1:-0}
      if ((max_len>255)); then
        max_len=255
      fi
      if ((max_len<0)); then
        max_len=0
      fi
      ;;
  -p|--preserve-case)
      preserve_case=1 ;;
  -n|--no-clobber)
      clobber=0 ;;
  -v|--verbose)
      VERBOSE=1 ;;
  -q|--quiet)
      VERBOSE=0 ;;
  -h|--help)
      show_help; exit 0 ;;
  -[smpnvqh]*) #split up single options
      set -- "${1:0:2}" "-${1:2}" "${@:2}"; continue ;;
  -*) die 22 "Invalid option ${1@Q}" ;;
  *)  Files+=("$1") ;;
esac; shift; done

((${#Files[@]})) || die 1 'No files found.'

info "WARNING: ${#Files[@]} files will be RENAMED in post-slug format!"
read -rp "$SCRIPT_NAME: Proceed? y/n "; [[ $REPLY == y ]] || exit 1
>&2 echo

for file in "${Files[@]}"; do
  file=$(realpath -e -- "$file")
  dirname=$(dirname -- "$file")
  newfile=$(basename -- "$file")
  ext=''
  if [[ $newfile == *"."* ]]; then
    ext=".${newfile##*.}"
    newfile=$(basename -s "$ext" -- "$newfile")
  fi

  slug=$(post_slug "$newfile" "$sep_char" "$preserve_case" "$max_len")
  if [[ -z $slug ]]; then
    info "WARNING: Zero length slug for ${file@Q}"
    continue
  fi
  newfile="$dirname/$slug$ext"

  if [[ $newfile == "$file" ]]; then
    ((!VERBOSE)) || info "No change required for ${file@Q}"
    continue
  fi

  if [[ -f $newfile ]] && ((!clobber)); then
    info "File '$(basename -- "$newfile")' already slugged"
    continue
  fi

  ((!VERBOSE)) || info "mv $file -> $newfile"
  mv "$file" "$newfile" || die 1 "Error moving ${file@Q} to ${newfile@Q}"
done

#fin
